### PR TITLE
Fixing multiple universal language display in dropdown

### LINKED ISSUE #1642: Language dropdown shows universal option 2 times
**Actual Behaviour**

Language dropdown shows universal option 2 times.

**Expected Behaviour**

Should show only a single option for universal.

**Steps to reproduce it**

On the home page , select language dropdown (side of search bar)

**Screenshots of the issue**

lang-issue

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by mkfeuhrer**
Fixes #1642 

Changes: Iterating from index 1 , since api call does not has valid language at 0 index.

Surge Deployment Link: https://pr-1643-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:

updatedlanbug

### CODE REVIEW

**Comment by mkfeuhrer** [comment]
@fragm3 there should be one option for universal right ? What needs to be fixed in the screenshot you have provided ?

**Comment by mkfeuhrer** [comment]
@fragm3 Updated !

File: src/components/BrowseSkill/BrowseSkill.js [hunk 1]
```diff
@@ -319,6 +319,10 @@ export default class BrowseSkill extends React.Component {
           data.sort();
           languages = [];
           for (let i = 0; i < data.length; i++) {
+            if (data[i] === '0' || data[i] === 'xx') {
```
Comment (tabesin) [inline src/components/BrowseSkill/BrowseSkill.js]: Please check if they are the same type, otherwise === would always return false.

Comment (mkfeuhrer) [reply src/components/BrowseSkill/BrowseSkill.js]: Done!

Comment (rossoskull) [reply src/components/BrowseSkill/BrowseSkill.js]: @mkfeuhrer, @tabesin meant to check the data-type of `data[i]`, if it is the same as a string, else with using `===` as comparator, the statement would always evaluate to false, as it also compares data-type.

File: src/components/BrowseSkill/BrowseSkill.js [hunk 2]
```diff
@@ -319,6 +319,10 @@ export default class BrowseSkill extends React.Component {
...
+              continue;
+            }
+            console.log(data[i]);
```
Comment (fragm3) [inline src/components/BrowseSkill/BrowseSkill.js]: Remove this

File: src/components/BrowseSkill/BrowseSkill.js (hunk 1 above)
Comment (mkfeuhrer) [reply src/components/BrowseSkill/BrowseSkill.js]: @rossoskull  @tabesin  I checked and ensured the datatypes of both by debugging . Since both are string === works fine here.
