### PR TITLE
Fix image upload in BotBuilder design view #2006

### LINKED ISSUE #2006: Fix image upload in BotBuilder design view
**Actual Behaviour**

For Setting Image in BotBuilder --> Design View(UI) --> Change background(Image) --> On uploading the image, image not getting saved.
Same for Choose your bot avatar in the same tab

**Expected Behaviour**

Fix it

**Steps to reproduce it**

For Setting Image in BotBuilder --> Design View(UI) --> Change background(Image) --> On uploading avatar image or bot background image

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2006

Changes: - Fix image upload of avatar, bot background

Surge Deployment Link: https://pr-2007-1-fossasia-susi-skill-cms.surge.sh

### CODE REVIEW

File: src/redux/reducers/create.js [hunk 1]
```diff
@@ -413,10 +413,9 @@ export default handleActions(
     },
 
     [actionTypes.CREATE_SET_BOT_BACKGROUND_IMAGE](state, { payload }) {
-      const response = payload;
-      const imagePath = { response };
+      const imagePath = payload.imagePath;
```
Comment (fragm3) [inline src/redux/reducers/create.js]: I would like to point out, `const {imagePath} = payload` was not working, so please ignore this one.

**Comment by harsh-jindal** [comment]
Screenshot 2019-05-28 at 9 43 45 AM

Fix this. Rest Looks good.

**Comment by fragm3** [comment]
@harsh-jindal fixed, please review
