### PR TITLE
Save changes in botbuilder tabs while navigating to other tabs

### LINKED ISSUE #1116: Save the changes made by the user while navigating from one tab to another
**Actual Behaviour**

When the user makes some changes in the "Build" page, and moves to other page, the progress made in the "Build" page is lost. Similarly for other pages also the progress is not saved.

**Expected Behaviour**

The changes made by the user should be saved even if the user switches between the menu options.

**Steps to reproduce it**

Make some changes in the "Build" page of the botbuilder. Then move to "Design" page and then come back to the "Build" page. The changes you made will be lost.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by hkedia321**
Fixes #1116 

Changes:
- save changes in `Build`, `Design`, `Configure` views while navigating from one tab to another.

Surge Deployment Link: https://pr-1247-fossasia-susi-skill-cms.surge.sh

### CODE REVIEW

File: src/components/BotBuilder/BotWizard.js [hunk 1]
```diff
@@ -76,6 +75,11 @@ class BotWizard extends React.Component {
       imageChanged: false,
       loaded: false,
       commitMessage: '',
+      skillCategory: null,
+      skillLanguage: '',
+      skillName: '',
+      code:
```
Comment (DNS-404) [inline src/components/BotBuilder/BotWizard.js]: Please revert this back to `buildCode` rather than `code` so that we know that which tab does it belong to. I think it make things more clear.

**Comment by hkedia321** [comment]
@DNS-404 Made the changes. Please check.
