### PR TITLE
Fixed wrong API call issues while changing status of any Skill from the Admin panel

### LINKED ISSUE #1387: API call issue while trying to change status of a skill from Admin Panel
**Actual Behaviour**

Currently, the query parameter `skill` is being passed `undefined` during the API call.

**Expected Behaviour**

Correct parameter value should be passed.

**Steps to reproduce it**

Try changing review status or edit status of any skill from the Admin Panel. You'll see API calls like following in the network tab: `https://api.susi.ai/cms/changeSkillStatus.json?model=general&group=Knowledge&language=en&skill=undefined&reviewed=false&editable=true&access_token=t5BAasiJejVz8K2Ph0Z8TbFiBvP8oF`

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Akshat-Jain**
Fixes #1387 

Changes: Fixed wrong API call issues while changing status of any Skill from the Admin panel. Now, correct value is passed for the query parameter `skill` while changing the review status or the edit status of the Skill.

Surge Deployment Link: https://pr-1388-fossasia-susi-skill-cms.surge.sh

### CODE REVIEW

**Comment by Akshat-Jain** [comment]
@akshatnitd Done. Please review. Thanks :-)

File: src/components/Admin/ListSkills/ListSkills.js [hunk 1]
```diff
@@ -247,6 +247,7 @@ class ListSkills extends React.Component {
           skillsData: skills,
           loading: false,
         });
+        console.log(skills);
```
Comment (hkedia321) [inline src/components/Admin/ListSkills/ListSkills.js]: Please remove this console log if it is not required.

Comment (Akshat-Jain) [reply src/components/Admin/ListSkills/ListSkills.js]: Done. Please review. Thanks :-)
