### PR TITLE
Fixes #927: Display latest skills on homepage

### LINKED ISSUE #927: Show the Latest Skills on the Home Page
**Actual Behaviour**
* Not shown now

**Expected Behaviour**
* Show the Latest Skills on the Home Page

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #927 

Changes: [Add here what changes were made in this issue and if possible provide links.]
Display latest skills on homepage

Surge Deployment Link: https://pr-1018-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
screenshot from 2018-07-09 11-30-02

### CODE REVIEW

File: src/components/BrowseSkill/BrowseSkill.js [hunk 1]
```diff
@@ -374,6 +376,30 @@ export default class BrowseSkill extends React.Component {
...
+      jsonp: 'callback',
+      crossDomain: true,
+      success: function(data) {
+        self.setState({
+          skillsLoaded: true,
+          latestSkills: data.filteredData,
+        });
+      },
+      error: function(e) {
+        console.log('Error while fetching top used skills', e);
```
Comment (anshumanv) [inline src/components/BrowseSkill/BrowseSkill.js]: `while latest recent skills`
