### PR TITLE
Fixes #858: Add links to Category on sidebar

### LINKED ISSUE #858: Add links to MenuItems to redirect to category page
**Actual Behaviour**
* Not present.

**Expected Behaviour**
* Add links to MenuItems to redirect to category page

**Steps to reproduce it**
NA

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #858 

Changes: 
* Add links to Category on sidebar to show category wise skills

Surge Deployment Link: https://pr-865-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
peek 2018-06-26 10-16

### CODE REVIEW

File: src/components/BrowseSkill/BrowseSkill.js [hunk 1]
```diff
@@ -121,22 +121,24 @@ export default class BrowseSkill extends React.Component {
...
-              value="All"
-              key="All"
-              primaryText="All"
-              onClick={event => this.handleGroupChange(event, 'All')}
-            />,
+            <Link to="/category/All" key="All">
+              <MenuItem
+                value="All"
+                primaryText="All"
+                onClick={event => this.handleGroupChange(event, 'All')}
```
Comment (anshumanv) [inline src/components/BrowseSkill/BrowseSkill.js]: onClick event is no longer needed now that we are transitioning the page, please remove. :+1:

**Comment by akshatnitd** [comment]
@anshumanv @Akshat-Jain Made the changes :+1:
