### PR TITLE
Image upload button only accepts images in skill creator

### LINKED ISSUE #1707: Image upload button should only accept images
**Actual Behaviour**
Image upload button accepts files of all types

**Expected Behaviour**
Image upload button should only accept images

**Steps to reproduce it**
Try uploading an image with non-image file type

**Screenshots of the issue**

screenshot 2018-12-05 at 3 44 33 pm

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by neeraj3029**
Fixes #1707 

Changes: [Add here what changes were made in this issue and if possible provide links.]
Image upload button only accepts images in skill creator

Surge Deployment Link: https://pr-1708-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
screenshot 2018-12-05 at 3 35 22 pm

### CODE REVIEW

File: src/components/SkillCreator/SkillCreator.js [hunk 1]
```diff
@@ -1295,6 +1295,7 @@ export default class SkillCreator extends Component {
                               >
                                 <input
                                   type="file"
+                                  accept="image/x-png,image/gif,image/jpeg"
```
Comment (anshumanv) [inline src/components/SkillCreator/SkillCreator.js]: Make it `image/*` instead for simplicity.

Comment (neeraj3029) [reply src/components/SkillCreator/SkillCreator.js]: Alright!

**Comment by neeraj3029** [comment]
@anshumanv Done.
