### PR TITLE
Backward button is working

### LINKED ISSUE #1686: Back navigation is not working
**Actual Behaviour**

When searched for a skill the backward navigation button is not working.

**Expected Behaviour**

Navigation Backward button should work. 

**Screenshots of the issue**

backward navigation

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #1686 

Changes: Navigation Backward button is working.

Surge Deployment Link: https://pr-1715-fossasia-susi-skill-cms.surge.sh
 
backward

### CODE REVIEW

File: src/components/BrowseSkill/BrowseSkill.js [hunk 1]
```diff
@@ -183,13 +183,12 @@ export default class BrowseSkill extends React.Component {
 
   handleNavigationBackward = () => {
     $('html, body').animate({ scrollTop: 0 }, 'fast');
-    const { listPage, listOffset, entriesPerPage, skills } = this.state;
```
Comment (akshatnitd) [inline src/components/BrowseSkill/BrowseSkill.js]: Why was the destructuring removed? Please use destructuring.

Also, you can use the following syntax here - 
```
this.setState( (prevState) => { listPage : prevState.listPage - 1 } );

```

Comment (samagragupta) [reply src/components/BrowseSkill/BrowseSkill.js]: @akshatnitd Done the changes.
