### PR TITLE
Logout is working, Refactored Skill Listing components to components …

### LINKED ISSUE #139: Logout button not working

### PR DESCRIPTION
**Pull request by dynamitechetan**
Fixes #139
Made the Logout working, Refactored Skill Listing components to components package.

### CODE REVIEW

File: src/components/Auth/Logout.js [hunk 1]
```diff
@@ -1,36 +1,35 @@
...
-    this.props.history.push('/');
-    window.location.reload();
-  }
-  render() {
+    componentDidMount(){
+        deleteCookie('loggedIn');
+        deleteCookie('serverUrl');
+        deleteCookie('email');
+        this.props.history.push('/');
+        window.location.reload();
```
Comment (DravitLochan) [inline src/components/Auth/Logout.js]: remove this!
