### PR TITLE
Refactor BrowseSkills, fix functionality, add new functionality #1733

### LINKED ISSUE #1733: Refactor BrowseSkills, fix functionality, add new functionality
**Actual Behaviour**

BrowseSkills need refactoring, changes to properly

**Expected Behaviour**

Implement:

- Add number of pages in New Arrivals

- Add ordering of the filters which appear

- Sort By Ascending/Descending

- Number of pages at the end of browse skills

- Add number of results for days filter.

Fix:

- Fix colour of icon - skill list or skill grid

- BrowseSkill code, refactor code

- On searching or adding filters and then choosing/applying SUSI category filter, the old filters gets removed.

Enhancement:

- Make top search bar, sort by filters, langauges responsive, skills per page, page responsive.

screenshot 2018-12-20 at 9 44 20 pm

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #1733 

Changes:

Added

- [x] Add number of pages in New Arrivals
- [x]  Sort By Ascending/Descending
- [x]  Number of pages at the end of browse skills
- [x]  Add number of results for days filter.

Improve
- [x]  Fix colour of icon - skill list or skill grid
- [ ]  On searching or adding filters and then choosing/applying SUSI category filter, the old filters gets removed. - This will be done using redux
-  [x]  Render scroll list using object to reduce code repetition
- [x] Use presentational component for rendering Rating Stars
- [ ] Make the top bar response(search bar, and other filters.

Surge Deployment Link: https://pr-1740-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:

### CODE REVIEW

File: src/components/BrowseSkill/BrowseSkill.js [hunk 1]
```diff
@@ -36,6 +39,41 @@ import './custom.css';
 
 const cookies = new Cookies();
 
+const Rating = props => {
```
Comment (akshatnitd) [inline src/components/BrowseSkill/BrowseSkill.js]: Make it a separate component.

File: src/components/BrowseSkill/BrowseSkill.js [hunk 2]
```diff
@@ -551,7 +601,20 @@ export default class BrowseSkill extends React.Component {
...
+        skillsLoaded: false,
+      }),
+      () => {
+        this.loadCards();
+      },
+    );
+  };
+
   render() {
+    console.log(this.state, 'STATE');
```
Comment (akshatnitd) [inline src/components/BrowseSkill/BrowseSkill.js]: Remove console.log

File: src/components/BrowseSkill/BrowseSkill.js [hunk 3]
```diff
@@ -36,6 +39,41 @@ import './custom.css';
 
 const cookies = new Cookies();
 
+const Rating = props => {
+  console.log(props, 'PROPS');
```
Comment (akshatnitd) [inline src/components/BrowseSkill/BrowseSkill.js]: Remove console.log
