### PR TITLE
Fix bugs on CMS home screen

### LINKED ISSUE #620: The ratings on skills home page only show integer values
**Actual Behaviour**
The ratings on skills home page only show integer values

**Expected Behaviour**
It should show float values

**Steps to reproduce it**
Open https://skills.susi.ai

**Screenshots of the issue**
screenshot from 2018-06-08 20-34-15
Here the rating received is 3.29

**Would you like to work on the issue?**
Yes

### LINKED ISSUE #629: The default category of home page is Knowledge and group filtering not working
**Actual Behaviour**
* The default category of home page is Knowledge.
* Also, filtering by group doesn't work when user comes back from Skill Detailed page.

**Expected Behaviour**
* The default category of home page should be `All`.
* Filtering should work for all cases

**Steps to reproduce it**
Open the page https://skills.susi.ai

**Screenshots of the issue**
NA

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #629
Fixes #620

Changes: 
* Parsed the average rating as float
* Changed default group as 'All'
* Fixed filtering issues

Surge Deployment Link: https://pr-630-fossasia-susi-skill-cms.surge.sh

Screenshots for the change:
screenshot from 2018-06-09 00-37-32

Note the rating here as 3.29

### CODE REVIEW

File: src/components/BrowseSkill/BrowseSkill.js [hunk 1]
```diff
@@ -261,23 +263,23 @@ export default class BrowseSkill extends React.Component {
                         description = 'No description available'
                     }
                     if (skill.skill_rating) {
-                        average_rating = parseInt(skill.skill_rating.stars.avg_star,10);
+                        average_rating = parseFloat(skill.skill_rating.stars.avg_star,10);
```
Comment (anshumanv) [inline src/components/BrowseSkill/BrowseSkill.js]: Is the `,10` param still relevant? :thinking:

Comment (akshatnitd) [reply src/components/BrowseSkill/BrowseSkill.js]: Have fixed it out. Thanks for pointing it out :+1: 
It gives a warning is parseInt without radix as the number can be Hex, Decimal, etc.
But praseFloat can only mean Decimal, hence the radix not required.
